#!/usr/bin/env python3
"""Write the input script that starts Mike Tyson's Punch-Out!! at a fight
selected by a pass key, from power-on to the bell (ADR-0239 section 1, rung 1:
the game's own selector, by input - not a cheat).

    python3 scripts/stages/punchout/pass-key.py "0057375423" out.txt \\
        [--confirm=A|ABS] [--idle=<frames>]

Why a generator and not a hand-written script: typing one pass key is 47-65
keypresses, and each one is 20 frames, so the file is ~100 lines of a single
button. The comments here are the record of why the shape is what it is.

The screen mechanics (measured on the user's dump, 2026-09-26; the game's
official manual p.6 says the same in prose - "use the left and right sides of
the control pad to select the pass key, then press the A or B button to input
the pass key", and the disassembly nmikstas/mike-tysons-punch-out-disassembly
PRG_BankDEF.asm LA370-LA406 does exactly this):

  * The title menu (NEW / CONTINUE) is up and waiting from frame 691; four
    Start presses during the boot reach it. Down moves the cursor to CONTINUE.
  * The pass key is ten digits shown 3-3-4. A or B writes the digit under the
    cursor and advances; Right increments that digit, Left decrements it
    (0 wraps to 9); the tenth A or B submits the pass key.
  * A pass key is therefore typed "increment to the digit, then confirm", and
    the first confirm arms the screen (RAM $04C2) rather than moving on.
  * 135 792 4680 (Another World Circuit) and 106 113 0120 (credits) are the two
    keys the ROM compares against its A+B+Select buffer, so their last press is
    A+B+Select instead of A.

After the pass key is accepted the game plays the circuit card ("PUSH START!"),
the fighter profile card and the ROUND 1 card, each waiting for Start, and then
the ring introduction, which is where the fight's own body script must begin.
`--idle` is the frames from the last keypress to the bell; it was measured by
minting save states along the way (runs/f1416/punchout/RESULT.md).

Pass keys are published values, cited per key in the profile that uses them
(scripts/stages/punchout/navigation.json). None is invented here.
"""
import sys

PRESS, GAP = 10, 10   # frames held / released; the PASS KEY screen wants the release
BOOT = 240            # idle before the first Start: the boot and the demo
STARTS_BOOT = 4       # Start presses that reach the title menu (frame 720)
MENU_AT = 720         # the menu is interactive from frame 691; 720 is the 4th press
# Frames from the last Start press to the bell. The ring introduction runs on
# its own after the third Start: at frame 3004 the referee is still centre-ring
# and at 3246 the two are already boxing, so the bell is ~3080 and the entry
# ends just before it - a body script pressed during the last seconds of the
# introduction is ignored, one pressed after the bell is a fight nobody can
# record (runs/f1416/punchout/RESULT.md).
DEFAULT_IDLE = 1050


def presses_for(digits: str, confirm: str) -> list:
    """The keypresses that type `digits` on the PASS KEY screen."""
    out = ["A"]                        # the first A arms the screen; digit 1 = 0
    for d in digits:
        out += ["R"] * int(d)          # Right increments the digit under the cursor
        out.append("A")                # input it and move to the next of ten
    out[-1] = confirm                  # the tenth input submits the pass key
    return out


def script(digits: str, confirm: str, idle: int) -> tuple:
    lines = [
        "# Mike Tyson's Punch-Out!! (MMC2, CHR ROM) from power-on to the bell of"
        f" the fight the pass key {digits[:3]} {digits[3:6]} {digits[6:]} starts.",
        "# Generated by scripts/stages/punchout/pass-key.py - do not edit by hand.",
        "#",
        "# The game's own selector (ADR-0239 section 1 rung 1): no RAM cheat is",
        "# involved, so the run is a clean pass and every ADR-0183 surface may read",
        "# it. Typing, per the manual and the disassembly: Down moves the title",
        "# cursor to CONTINUE, A/B input the digit under the cursor and advance,",
        "# Right increments it, Left decrements it, the tenth A/B submits.",
        f"# {idle} frames of ring introduction follow the last keypress, then the",
        "# fight's body script begins at the bell.",
        "",
        f"{BOOT}f -",
    ]
    for i in range(STARTS_BOOT):
        lines += [f"{PRESS}f T", f"110f -"]
    lines += [f"{PRESS}f D", "40f -"]        # NEW -> CONTINUE
    seq = presses_for(digits, confirm)
    for i, k in enumerate(seq):
        if i == len(seq) - 1:
            lines.append(f"# the tenth input submits the pass key"
                         f"{' (A+B+Select: an A+B+Select key)' if k == 'ABS' else ''}")
        lines += [f"{PRESS}f {k}", f"{GAP}f -"]
    # circuit card -> profile card -> ROUND card, each waiting for Start
    lines += ["60f -", f"{PRESS}f T", "120f -", f"{PRESS}f T", "120f -", f"{PRESS}f T"]
    lines += [f"{idle}f -"]
    frames = (BOOT + STARTS_BOOT * (PRESS + 110) + PRESS + 40
              + len(seq) * (PRESS + GAP) + 320 + idle)
    return "\n".join(lines) + "\n", frames, len(seq)


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--"))
    if len(args) != 2:
        print(__doc__)
        return 2
    digits = args[0].replace(" ", "").replace("-", "")
    if len(digits) != 10 or not digits.isdigit():
        print(f"refused: {args[0]!r} is not ten digits", file=sys.stderr)
        return 2
    text, frames, n = script(digits, opts.get("confirm", "A"),
                             int(opts.get("idle", DEFAULT_IDLE)))
    open(args[1], "w").write(text)
    print(f"{args[1]}: {n} keypresses, {frames} frames "
          f"({frames / 60.0988:.1f} s), bell at the end")
    return 0


if __name__ == "__main__":
    sys.exit(main())
