#!/usr/bin/env python3
"""Every renderer that runs a librashader chain must consult IsLookCompare.

ADR-0246 §5 (Hold to Compare): while the button is held the shader chain is
bypassed rather than rebuilt, because the measured swap stutters (crt-geom
`SetShader` 67.6 ms and 17.6 ms against a 16.7 ms frame, `make
metal-presenter-tests`). macOS kept that promise from the start - its renderer
sets the presenter's bypass - and Windows and Linux did not, so §5 held on one
platform of three with nothing to notice it. Closed 2026-10-05: both renderers
now read the flag.

The appliers are found by scanning the repo rather than a list of platform
directories, and the set found is then compared against EXPECTED_APPLIERS, which
is written down. Deriving alone is not enough: a call can be hidden from any
text search (built by concatenation, reached through a table of function
pointers, generated by a macro that never spells the symbol), and an applier set
that silently grew or silently emptied looks exactly like a clean run. So an
unlisted applier is a FAILURE, not a discovery - adding a renderer is a
deliberate act that forces this file to be updated, which is the moment the read
is checked. The same mechanism catches the other direction: remove the vendored
bindings exclusion by accident and unrelated files appear, loudly.

Text is reduced before matching, because a mention is not a call:
  * comments are removed, so deleting a real read while leaving a comment that
    names it fails instead of passing;
  * the CONTENTS of string and char literals are removed - a call cannot live
    inside a string, and `scripts/core_unit_tests.cpp` contains
    "mtl_filter_chain_frame failed: ..." messages that would otherwise read as
    eight appliers - with `R"(...)"` raw strings blanked first, so an odd quote
    inside one cannot desynchronise the walk;
  * `#if 0` regions are removed;
  * a `//` comment continued with a backslash is followed to its real end.

This is still a presence guard, and these are its limits, written down rather
than implied:

  * It sees THAT the flag is read, not what is done with it. On macOS, replacing
    `_presenter.SetShaderBypass(_emu->GetSettings()->IsLookCompare());` with
    `bool unused = IsLookCompare(); (void)unused;` passes, and the presenter is
    never told to bypass. That wiring is what `make metal-presenter-tests` is
    for, and it pins the presenter half rather than this call site.
  * It cannot see a read reached through a pointer to the member function, nor a
    read copied into a local in another file.
  * `#if defined(NEVER)` is not `#if 0`; only the literal zero is stripped.
  * It cannot tell a chain whose call is gone from one whose call is hidden, and
    says so rather than guessing, because both are FAILs.

Windows and Linux are compiled only when a pull request targets `prod` -
`.github/workflows/build.yml` runs on that base branch and on manual dispatch,
never on a pull request into `main` - so they are not compiled by a normal pull
request either. They are never run here, and neither has a renderer harness.
"""

import pathlib
import re
import sys

#Every file that must be found running a chain. Written down on purpose - see the
#module comment. Update this list in the same commit that adds a renderer.
EXPECTED_APPLIERS = (
	"Linux/LinuxOglRenderer.cpp",
	"MacOS/MetalPresenter.mm",
	"Windows/Renderer.cpp",
)

#The one applier whose flag read lives in another file: macOS's presenter runs the
#chain and its renderer reads the flag and sets the presenter's bypass. An explicit
#map rather than a directory-wide rule, so a second renderer in MacOS/ cannot pass
#on the strength of the first one's read.
DELEGATED_READ = {
	"MacOS/MetalPresenter.mm": "MacOS/MacOSMetalRenderer.mm",
}

#The vendored librashader bindings are nothing but *_filter_chain_frame typedefs and
#declarations, not a renderer - named one by one, not by directory, because
#Utilities/Video/ also holds project-owned code.
EXCLUDED_FILES = (
	"Utilities/Video/librashader.h",
	"Utilities/Video/librashader_ld.h",
)

#Directories never walked. Matched against the path RELATIVE to the repo root, so a
#checkout that happens to live under a folder called `bin` is unaffected. `roms` is
#unversioned local content (it holds a virtualenv with 100k+ files) and the graph
#cache is generated.
SKIPPED_DIRS = {
	"obj", "bin", "build", "node_modules", ".git", ".venv", "venv",
	"player-renders", "graphify-out", "roms", ".claude", "out",
	"runs", "runs-archive",
}

SOURCES = (".cpp", ".h", ".hpp", ".hh", ".hxx", ".ipp", ".inl", ".mm", ".m",
	".cc", ".cxx", ".c", ".cs", ".swift")

#The bare symbol, with or without a call: a chain wrapped in a macro
#(`LIBRA_CALL(gl_filter_chain_frame)`) does not put a parenthesis after the name,
#and that is a real way to hide one.
APPLIES = re.compile(r"\b\w*_filter_chain_frame\b")
READS = re.compile(r"\bIsLookCompare\s*\(")

RAW_STRING = re.compile(r"R\"(?P<delim>[^()\\\s]{0,16})\(.*?\)(?P=delim)\"", re.DOTALL)
IF_ZERO = re.compile(r"^[ \t]*#[ \t]*if[ \t]+0\b.*?^[ \t]*#[ \t]*endif\b",
	re.DOTALL | re.MULTILINE)


def blank_literals_and_comments(text: str) -> str:
	"""Remove comments, string/char literal contents and `#if 0` regions.

	Walking beats a regex here: a `//` inside a string is not a comment, and a
	quote inside a comment does not open a string. The walk keeps literals'
	delimiters and drops their contents, so a symbol named inside a message
	disappears while the code around it stays where it was.
	"""
	text = IF_ZERO.sub("", text)
	text = RAW_STRING.sub('R""', text)

	out = []
	i, n = 0, len(text)
	quote = ""
	while i < n:
		ch = text[i]
		if quote:
			if ch == "\\" and i + 1 < n:
				i += 2
				continue
			if ch == quote:
				out.append(ch)
				quote = ""
			i += 1
			continue
		if ch == '"':
			quote = '"'
			out.append(ch)
			i += 1
			continue
		if ch == "'":
			#A closing quote within four characters is a char literal;
			#anything else is an apostrophe (`don't`) or a C++14 digit
			#separator (`1'000`), neither of which opens a literal.
			close = re.compile(r"\A'(?:\\.|[^'\\\n])'").match(text, i)
			if close:
				out.append("''")
				i = close.end()
				continue
			out.append(ch)
			i += 1
			continue
		if ch == "/" and i + 1 < n and text[i + 1] == "/":
			#A line comment ends at the newline unless it is continued with a
			#backslash, in which case the NEXT line is comment too - breaking at
			#the backslash would scan that line as code and count its read.
			while i < n:
				if text[i] == "\\" and i + 1 < n and text[i + 1] == "\n":
					i += 2
					continue
				if text[i] == "\n":
					break
				i += 1
			continue
		if ch == "/" and i + 1 < n and text[i + 1] == "*":
			i += 2
			while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
				i += 1
			i += 2
			continue
		out.append(ch)
		i += 1
	return "".join(out)


def sources_in(root: pathlib.Path):
	for path in root.rglob("*"):
		if not path.is_file() or path.suffix.lower() not in SOURCES:
			continue
		relative = path.relative_to(root).as_posix()
		if relative in EXCLUDED_FILES:
			continue
		parent_parts = pathlib.PurePosixPath(relative).parts[:-1]
		if any(part in SKIPPED_DIRS for part in parent_parts):
			continue
		yield path, relative


def main() -> int:
	root = pathlib.Path(__file__).resolve().parents[2]
	appliers = {}
	readers = set()

	for path, relative in sources_in(root):
		text = blank_literals_and_comments(path.read_text(encoding="utf-8", errors="replace"))
		if APPLIES.search(text):
			appliers[relative] = pathlib.PurePosixPath(relative).parent.as_posix()
		if READS.search(text):
			readers.add(relative)

	failures = []
	expected = set(EXPECTED_APPLIERS)

	for applier in sorted(set(appliers) - expected):
		failures.append(
			f"{applier} runs a librashader chain and is not in EXPECTED_APPLIERS. "
			f"If it is a renderer, add it there and make it read IsLookCompare() - "
			f"Hold to Compare (ADR-0246 §5) presents the filtered frame otherwise."
		)

	for applier in sorted(expected - set(appliers)):
		failures.append(
			f"{applier} is listed in EXPECTED_APPLIERS but no longer runs a "
			f"*_filter_chain_frame. Either its chain is gone, or the call is hidden "
			f"from this search (built by concatenation, reached through a function "
			f"pointer), and this guard cannot tell the two apart."
		)

	for applier in sorted(expected & set(appliers)):
		if applier in readers:
			continue
		delegated = DELEGATED_READ.get(applier)
		if delegated and delegated in readers:
			continue
		if delegated:
			failures.append(
				f"{applier} runs a librashader chain and delegates its flag read to "
				f"{delegated}, which no longer reads IsLookCompare()."
			)
		else:
			failures.append(
				f"{applier} runs a librashader chain but does not read "
				f"IsLookCompare(), so Hold to Compare (ADR-0246 §5) presents the "
				f"filtered frame there."
			)

	if failures:
		for failure in failures:
			print(f"FAIL: {failure}", file=sys.stderr)
		return 1

	for applier in sorted(expected):
		where = "same file" if applier in readers else DELEGATED_READ[applier]
		print(f"ok: {applier} presents a shader chain and IsLookCompare() is read in {where}")
	print(f"ok: the applier set is exactly the {len(expected)} written-down appliers")
	return 0


if __name__ == "__main__":
	sys.exit(main())
